name: Deploy Web Frontend

on:
  workflow_dispatch:   # Manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hikiuzrx
          password: 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

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_APP_API_URL="${{ secrets.VITE_APP_API_URL }}" \
            --build-arg VITE_APP_HTTP_API_URL="${{ secrets.VITE_APP_HTTP_API_URL }}" \
            --build-arg VITE_APP_STORAGE_URL="${{ secrets.VITE_APP_STORAGE_URL }}" \
            --build-arg VITE_APP_ENCRYPTION_KEY="${{ secrets.VITE_APP_ENCRYPTION_KEY }}" \
            --build-arg VITE_APP_BASE_LAYOUT_CONFIG_KEY="${{ secrets.VITE_APP_BASE_LAYOUT_CONFIG_KEY }}" \
            --build-arg VITE_APP_I18N_CONFIG_KEY="${{ secrets.VITE_APP_I18N_CONFIG_KEY }}" \
            -t ghcr.io/hikiuzrx/asc-web:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/hikiuzrx/asc-web:latest
