name: Build & Deploy

on:
  push:
    branches:
      - v1/asc

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitLab Registry
        run: |
          echo "${{ secrets.GITLAB_REGISTRY_PASSWORD }}" | \
            docker login registry.gitlab.com \
            -u ${{ secrets.GITLAB_REGISTRY_USER }} \
            --password-stdin

      - name: Build and push image
        run: |
          docker build -t registry.gitlab.com/zbousmina/asc:frontend .
          docker push registry.gitlab.com/zbousmina/asc:frontend

      - name: Deploy to Target Server via Jump Host
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          proxy_host: ${{ secrets.JUMP_HOST }}
          proxy_username: ${{ secrets.JUMP_USER }}
          proxy_pass: ${{ secrets.JUMP_PASSWORD }}
          script: |
            docker login registry.gitlab.com \
              -u ${{ secrets.GITLAB_REGISTRY_USER }} \
              -p ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

            docker pull registry.gitlab.com/zbousmina/asc:frontend
            cd /mnt/disk/production/apps/asc
            ls -la